#define PERMISSIVE_HOLD

#define QUICK_TAP_TERM 0

#define USB_SUSPEND_WAKEUP_DELAY 0
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "dWJQ9/bvZl35"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

